version: '3'

services:
  web:
    build: .
    command: ["sh", "scripts/start.sh"]
    container_name: api
    volumes:
      - .:/api
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.9-alpine
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  celery:  
    build: .
    command: celery -A api worker --loglevel=info
    container_name: celery
    volumes:
      - .:/api
    restart: always
    depends_on:
      - rabbitmq  


volumes:
  pgdata: {}
  rabbitmq_data: {}
