# Generated by Django 4.2.2 on 2023-06-19 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
